service: voa-feedparser

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  profile: excella

functions:
  articles:
    handler: handler.articles
    events:
      - http:
          path: articles
          method: get